#!/usr/bin/env python3
"""Embed handwritten MSL verbatim; its digest participates in ShaderRD's cache key."""
import hashlib
from pathlib import Path
import sys

source, target = map(Path, sys.argv[1:])
text = source.read_text()
assert ')KILN_MSL"' not in text
digest = hashlib.sha256(text.encode()).hexdigest()
header = ('// Generated by kiln/tools/build_metal_shader.py. Do not edit.\n'
          '#pragma once\n'
          f'#define KILN_NATIVE_SPECULAR_SHA256 "{digest}"\n'
          'static const char kiln_native_specular_msl[] = R"KILN_MSL(' + text + ')KILN_MSL";\n')
if not target.exists() or target.read_text() != header:
    target.write_text(header)
