#!/usr/bin/env python3
"""Build engine ShaderRD variants from the retained Kiln compute sources."""
from pathlib import Path
ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / 'servers/rendering/renderer_rd/kiln/sources'
STAGES = ['surfel_update', 'surfel_grid', 'surfel_generate', 'surfel_trace', 'surfel_integrate', 'surfel_evaluate', 'surfel_publish', 'surfel_specular', 'surfel_specular_filter', 'surfel_debug', 'sequence_lut', 'xegtao_depth', 'xegtao_main', 'xegtao_denoise', 'xegtao_temporal', 'bvh_refit', 'surfel_grid_prefix', 'surfel_grid_prefix_sums', 'surfel_grid_scatter', 'surfel_diffuse_filter', 'nrd_prepare', 'nrd_diffuse', 'nrd_resolve', 'surfel_spatial', 'surfel_schedule', 'query_validate', 'kajiya_sky', 'kajiya_surfel_clear_pool', 'kajiya_surfel_find_missing', 'kajiya_surfel_args', 'kajiya_surfel_age', 'kajiya_surfel_allocate', 'kajiya_surfel_clear_cells', 'kajiya_surfel_count_cells', 'kajiya_surfel_scan', 'kajiya_surfel_scan_segments', 'kajiya_surfel_scan_merge', 'kajiya_surfel_slot_cells', 'kajiya_surfel_trace', 'kajiya_surfel_resolve']
parts = ['#[compute]\n#version 460\n#VERSION_DEFINES\n#ifdef KILN_HARDWARE_RAY_QUERY\n#extension GL_EXT_ray_query : require\n#endif\n']
for stage in STAGES:
    text = (SOURCE / (stage + '.comp')).read_text().replace('#version 450', '')
    for inc in SOURCE.glob('*.inc'):
        text = text.replace('// @' + inc.stem.upper() + '@', inc.read_text())
    text = text.replace('// @PROJECT_SKY@', (ROOT / 'kiln/demo/rendering/sky/sky_radiance.gdshaderinc').read_text())
    assert '// @' not in text, stage
    parts.append('#ifdef STAGE_' + stage.upper() + '\n' + text + '\n#endif\n')
output = ROOT / 'servers/rendering/renderer_rd/shaders/kiln_gi.glsl'
text = '// Generated by kiln/tools/build_gi_shaders.py. Edit servers/rendering/renderer_rd/kiln/sources instead.\n' + '\n'.join(parts)
if not output.exists() or output.read_text() != text:
    output.write_text(text)
