#!/usr/bin/env python3
"""Build engine ShaderRD variants from the retained Kiln compute sources."""
from pathlib import Path
ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / 'servers/rendering/renderer_rd/kiln/sources'
STAGES = ['bvh_refit', 'kiln_sky', 'kiln_surfel_clear_pool', 'kiln_surfel_find_missing', 'kiln_surfel_args', 'kiln_surfel_age', 'kiln_surfel_allocate', 'kiln_surfel_clear_cells', 'kiln_surfel_count_cells', 'kiln_surfel_scan', 'kiln_surfel_scan_segments', 'kiln_surfel_scan_merge', 'kiln_surfel_slot_cells', 'kiln_surfel_trace', 'kiln_restir_trace', 'kiln_restir_temporal', 'kiln_restir_spatial', 'kiln_restir_resolve', 'kiln_brdf_lut', 'kiln_light', 'kiln_rtdgi_reproject', 'kiln_rtdgi_temporal_filter', 'kiln_rtdgi_spatial_filter', 'kiln_rtdgi_validity', 'kiln_rtr_trace', 'kiln_rtr_temporal', 'kiln_rtr_resolve', 'kiln_rtr_filter', 'kiln_rtr_cleanup', 'kiln_ssgi', 'kiln_ssgi_spatial', 'kiln_ssgi_upsample', 'kiln_ssgi_temporal', 'kiln_shadow_trace', 'kiln_shadow_bitpack', 'kiln_shadow_temporal', 'kiln_shadow_spatial', 'kiln_taa_reproject', 'kiln_taa_input', 'kiln_taa_history', 'kiln_taa_prob', 'kiln_taa_prob_filter', 'kiln_taa_prob_filter2', 'kiln_taa', 'kiln_display_lut', 'kiln_post', 'kiln_post_blur0', 'kiln_post_blur', 'kiln_post_reverse', 'kiln_rtdgi_history_reproject', 'kiln_wrc_trace', 'kiln_velocity_reduce_x', 'kiln_velocity_reduce_y', 'kiln_velocity_dilate', 'kiln_motion_blur']
parts = ['#[compute]\n#version 460\n#VERSION_DEFINES\n#ifdef KILN_HARDWARE_RAY_QUERY\n#extension GL_EXT_ray_query : require\n#endif\n']
for stage in STAGES:
    text = (SOURCE / (stage + '.comp')).read_text().replace('#version 450', '').replace('#version 460', '')
    for inc in SOURCE.glob('*.inc'):
        text = text.replace('// @' + inc.stem.upper() + '@', inc.read_text())
    assert '// @' not in text, stage
    parts.append('#ifdef STAGE_' + stage.upper() + '\n' + text + '\n#endif\n')
output = ROOT / 'servers/rendering/renderer_rd/shaders/kiln_gi.glsl'
text = '// Generated by kiln/tools/build_gi_shaders.py. Edit servers/rendering/renderer_rd/kiln/sources instead.\n' + '\n'.join(parts)
if not output.exists() or output.read_text() != text:
    output.write_text(text)
