#!/usr/bin/env python3
"""Build engine ShaderRD variants from the retained Kiln compute sources."""
from pathlib import Path
ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / 'servers/rendering/renderer_rd/kiln/sources'
STAGES = ['prepare_receivers', 'trace_primary', 'integrate', 'sh_temporal', 'update_world_cache', 'sh_filter', 'sh_decode', 'brdf_lut', 'sequence_lut', 'publish', 'xegtao_depth', 'xegtao_main', 'xegtao_denoise', 'xegtao_temporal']
parts = ['#[compute]\n#version 450\n#VERSION_DEFINES\n']
for stage in STAGES:
    text = (SOURCE / (stage + '.comp')).read_text().replace('#version 450', '')
    for inc in SOURCE.glob('*.inc'):
        text = text.replace('// @' + inc.stem.upper() + '@', inc.read_text())
    text = text.replace('// @PROJECT_SKY@', (ROOT / 'kiln/demo/rendering/sky/sky_radiance.gdshaderinc').read_text())
    assert '// @' not in text, stage
    parts.append('#ifdef STAGE_' + stage.upper() + '\n' + text + '\n#endif\n')
output = ROOT / 'servers/rendering/renderer_rd/shaders/kiln_gi.glsl'
text = '// Generated by kiln/tools/build_gi_shaders.py. Edit kiln/sources instead.\n' + '\n'.join(parts)
if not output.exists() or output.read_text() != text:
    output.write_text(text)
