#!/usr/bin/env python3
"""Prepare a separate, explicitly normalized Cornell diagnostic input.

The raw reference car contains coincident faces with opposite winding. Keep the
face whose winding agrees with the supplied vertex normals, then source order.
When opposite sides have different materials, retain the selected face's material.
Both renderers must load this same derived glTF; it is not raw-reference parity.
"""
from pathlib import Path
import argparse
import hashlib
import json
import subprocess
import numpy as np

ROOT = Path(__file__).resolve().parents[1] / 'cornell/assets'


def prepare(name):
    source = ROOT / 'prepared'
    destination = ROOT / 'canonical'
    destination.mkdir(exist_ok=True)
    doc = json.loads((source / (name + '.gltf')).read_text())
    payload = bytearray((source / (name + '.bin')).read_bytes())

    def accessor(index):
        a = doc['accessors'][index]
        v = doc['bufferViews'][a['bufferView']]
        components = 3 if a['type'] == 'VEC3' else 1
        return np.frombuffer(payload, '<f4' if a['componentType'] == 5126 else '<u4',
                             a['count'] * components, v['byteOffset']).copy().reshape(-1, components)

    source_count, result_count = 0, 0
    entries, all_keys, all_alignment = [], [], []
    for primitive in doc['meshes'][0]['primitives']:
        positions = accessor(primitive['attributes']['POSITION'])
        normals = accessor(primitive['attributes']['NORMAL'])
        indices = accessor(primitive['indices']).reshape(-1, 3)
        triangles = positions[indices]
        order = np.lexsort((triangles[:, :, 2], triangles[:, :, 1], triangles[:, :, 0]), axis=1)
        canonical = np.take_along_axis(triangles, order[:, :, None], axis=1)
        keys = np.ascontiguousarray(canonical).reshape(-1, 9).view(np.dtype((np.void, 36))).reshape(-1)
        face = np.cross(triangles[:, 1] - triangles[:, 0], triangles[:, 2] - triangles[:, 0])
        alignment = np.sum(face * normals[indices].sum(axis=1), axis=1)
        entries.append((primitive, indices))
        all_keys.append(keys)
        all_alignment.append(alignment > 0)
        source_count += len(indices)
    keys = np.concatenate(all_keys)
    _, inverse = np.unique(keys, return_inverse=True)
    priority = np.lexsort((np.arange(source_count), -np.concatenate(all_alignment).astype('i4'), inverse))
    _, first = np.unique(inverse[priority], return_index=True)
    selected = np.zeros(source_count, bool)
    selected[priority[first]] = True
    result_count = int(selected.sum())
    offset = 0
    for primitive, indices in entries:
        kept = indices[selected[offset:offset+len(indices)]].astype('<u4').reshape(-1)
        offset += len(indices)
        if not len(kept):
            doc['meshes'][0]['primitives'].remove(primitive)
            continue
        # Append new index data without changing the shared vertex/material input.
        a = doc['accessors'][primitive['indices']]
        a['bufferView'] = len(doc['bufferViews'])
        a['count'] = len(kept)
        doc['bufferViews'].append({'buffer': 0, 'byteOffset': len(payload), 'byteLength': kept.nbytes})
        payload.extend(kept.tobytes())
    digest = hashlib.sha256(payload).hexdigest()
    doc['buffers'][0]['byteLength'] = len(payload)
    doc['asset']['generator'] = 'Kiln shared canonical Cornell diagnostic input'
    doc['asset']['extras'] = {'payload_sha256': digest, 'coincident_faces_removed': source_count-result_count}
    for path, data in [(destination/(name+'.bin'), payload),
                       (destination/(name+'.gltf'), json.dumps(doc, separators=(',', ':')).encode())]:
        if not path.exists() or path.read_bytes() != data:
            path.write_bytes(data)
    config = (source/(name+'.gltf.import')).read_text()
    # Importer IDs/destinations are generated by Godot for the new source path.
    params = config.split('[params]', 1)[1]
    (destination/(name+'.gltf.import')).write_text('[remap]\nimporter="scene"\nimporter_version=2\ntype="PackedScene"\n\n[params]'+params)
    return {'name': name, 'original_triangles': source_count, 'canonical_triangles': result_count,
            'source_sha256': hashlib.sha256((source/(name+'.bin')).read_bytes()).hexdigest(),
            'canonical_sha256': digest}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--bake-output', type=Path, required=True, help='temporary directory for the reference baker outputs')
    parser.add_argument('--baker', type=Path, default=ROOT.parents[3]/'kajiya/target/release/bake.exe')
    args = parser.parse_args()
    rows = [prepare('cornell_box'), prepare('car')]
    (ROOT/'canonical/provenance.json').write_text(json.dumps(rows, indent=2)+'\n')
    args.bake_output.mkdir(parents=True, exist_ok=True)
    for name, baked_name in [('cornell_box', 'cornell_box'), ('car', '336_lrm')]:
        subprocess.run([str(args.baker.resolve()), '--scene', str(ROOT/'canonical'/(name+'.gltf')),
                        '--scale', '1', '-o', baked_name], cwd=args.bake_output, check=True)
    manifest = {'input': 'canonical', 'meshes': rows,
                'baker_sha256': hashlib.sha256(args.baker.read_bytes()).hexdigest(),
                'scene_inputs': {p.name: hashlib.sha256(p.read_bytes()).hexdigest()
                                 for p in sorted((ROOT/'canonical').glob('*')) if p.suffix in ('.bin', '.gltf')}}
    (args.bake_output/'cornell-inputs.json').write_text(json.dumps(manifest, indent=2)+'\n')
    print(json.dumps(rows, indent=2))


if __name__ == '__main__':
    main()
