#version 450
// @GI_COMMON@
#define GI_DIRTY_BINDING 5
// @GI_DIRTY@
layout(local_size_x=8,local_size_y=8,local_size_z=1) in;
layout(set=0,binding=1) uniform sampler2D input_sh;
layout(set=0,binding=2) uniform sampler2D normals;
layout(set=0,binding=3) uniform sampler2D visibility;
layout(set=0,binding=4,rgba16f) uniform writeonly image2D output_irradiance;
void main(){
    ivec2 q=ivec2(gl_GlobalInvocationID.xy),size=ivec2(p.debug.yz);
    if(any(greaterThanEqual(q,size)))return;
    if(p.gi.z>0.0 && !filter_region_dirty(q))return;
    vec3 irradiance=evaluate_original_sh(texelFetch(input_sh,q,0),texelFetch(input_sh,q+ivec2(size.x,0),0),
        texelFetch(input_sh,q+ivec2(size.x*2,0),0),texelFetch(normals,q,0).xyz);
    imageStore(output_irradiance,q,vec4(irradiance,1.0-texelFetch(visibility,q,0).r));
}
