#version 450
// @GI_COMMON@
// @SURFEL_DATA@
layout(local_size_x = 8, local_size_y = 8) in;
shared uint scan[64];
void main() {
	uint lane = gl_LocalInvocationIndex;
	uint block = gl_WorkGroupID.y * gl_NumWorkGroups.x + gl_WorkGroupID.x;
	uint key = block * 64u + lane;
	uint count = cell_heads[key].x;
	scan[lane] = count;
	barrier();
	for (uint step = 1u; step < 64u; step <<= 1u) {
		uint addend = lane >= step ? scan[lane - step] : 0u;
		barrier();
		scan[lane] += addend;
		barrier();
	}
	cell_heads[key] = uvec2(0u, scan[lane] - count);
	if (lane == 63u) grid_sums[block] = scan[lane];
}
